name: clinic_test_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebaseapis: ^0.1.2
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  flutter_feather_icons: ^2.0.0+1
  freezed_annotation: ^2.1.0
  flutter_riverpod: ^1.0.4
  auto_route: ^5.0.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.1.1
  loading_animation_widget: ^1.2.0+3
  flutter_lorem: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
