// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhxVjc3q3B2LNAluwYQxuFmFdV3_lMj2I',
    appId: '1:570597767661:web:05085c2e7032696f554fe4',
    messagingSenderId: '570597767661',
    projectId: 'clinic-test-app-bcdd8',
    authDomain: 'clinic-test-app-bcdd8.firebaseapp.com',
    storageBucket: 'clinic-test-app-bcdd8.appspot.com',
    measurementId: 'G-R2LQ9N4S80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtc9UxGKMAXZVzesBsobTIagFvKD6tw8',
    appId: '1:570597767661:android:354eba85b4536fca554fe4',
    messagingSenderId: '570597767661',
    projectId: 'clinic-test-app-bcdd8',
    storageBucket: 'clinic-test-app-bcdd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQI924W4xyVw6p92RuIfYDHKAmju7Sck',
    appId: '1:570597767661:ios:8c95b4d2f55c1912554fe4',
    messagingSenderId: '570597767661',
    projectId: 'clinic-test-app-bcdd8',
    storageBucket: 'clinic-test-app-bcdd8.appspot.com',
    iosClientId: '570597767661-859eaq9c76lhpdjh09n4kkis6oaso9o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinicTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhQI924W4xyVw6p92RuIfYDHKAmju7Sck',
    appId: '1:570597767661:ios:8c95b4d2f55c1912554fe4',
    messagingSenderId: '570597767661',
    projectId: 'clinic-test-app-bcdd8',
    storageBucket: 'clinic-test-app-bcdd8.appspot.com',
    iosClientId: '570597767661-859eaq9c76lhpdjh09n4kkis6oaso9o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinicTestApp',
  );
}
